### ISSUE TITLE
Where is the implementation of the authentication

### ISSUE THREAD

**Issue by ChrCode** [tylerebowers/TD-Ameritrade-API-Python-Wrapper#1]
Hello and thank you,

Your video and github are helpful. I have been working with Python to connect to my TD account.

Your video, show a bit how you authenticate and get your token, but I am not sure if that part of the process still works. Is this authentication part of your new design? Or are you doing manually on the side?

I am still trying to find the front door...

**Comment by tylerebowers** [comment]
The authentication flow is done in apis/client.py; its is called in main.py via client.login(). you must have your credentials in the variables/globals.py file.

If you are not going to do streaming then besides the imports all you need in main  .py would be client.login() and a quote.getQuote("ticker"). 

Planning on releasing a new video and finishing the api section of the code by the end of next week since my youtube videos are outdated.
